from sounds import sounds
sounds.play_sound(0)
raw_input("Press Enter to continue...")
sounds.play_sound(1)
raw_input("Press Enter to continue...")
sounds.play_sound(2)
raw_input("Press Enter to continue...")
sounds.play_sound(3)
raw_input("Press Enter to continue...")
sounds.play_sound(4)
